-- ==============================================================================
-- Supabase Schema for Comic Translation Studio
-- Tables: mask_corrections, quality_gate_events, character_profiles, terminology_store
-- ==============================================================================

-- 1. mask_corrections table (replaces mask_correction_memory.json)
-- Records manual mask edits (Scissors / Smart Brush) for persistent learning.
CREATE TABLE IF NOT EXISTS mask_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page TEXT,
    timestamp DOUBLE PRECISION,
    tool_used TEXT,
    bubble_id INTEGER,
    original_contour JSONB DEFAULT '[]'::jsonb,
    corrected_contours JSONB DEFAULT '[]'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mask_corrections_page ON mask_corrections (page);
CREATE INDEX IF NOT EXISTS idx_mask_corrections_tool ON mask_corrections (tool_used);
CREATE INDEX IF NOT EXISTS idx_mask_corrections_timestamp ON mask_corrections (timestamp);

-- 2. quality_gate_events table (replaces quality_gate_log.json)
-- Logs every quality gate pattern detection, auto-fix, and review flag.
CREATE TABLE IF NOT EXISTS quality_gate_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page TEXT,
    pattern_name TEXT,
    stage TEXT,
    severity TEXT,
    action_taken TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    bubble_id INTEGER,
    timestamp DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quality_gate_events_page ON quality_gate_events (page);
CREATE INDEX IF NOT EXISTS idx_quality_gate_events_pattern ON quality_gate_events (pattern_name);
CREATE INDEX IF NOT EXISTS idx_quality_gate_events_severity ON quality_gate_events (severity);

-- 3. character_profiles table (replaces character_profiles.py data file / character_memory.json)
-- Stores character voice personas, learned facts, and sample lines.
CREATE TABLE IF NOT EXISTS character_profiles (
    character_name TEXT PRIMARY KEY,
    voice_traits JSONB DEFAULT '[]'::jsonb,
    established_facts JSONB DEFAULT '[]'::jsonb,
    sample_lines JSONB DEFAULT '[]'::jsonb,
    visual_signature JSONB,
    aliases JSONB DEFAULT '[]'::jsonb,
    phrase_replacements JSONB DEFAULT '[]'::jsonb,
    exact_lines JSONB DEFAULT '{}'::jsonb,
    forbidden_tones JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. terminology_store table (replaces terminology_store.json)
-- Canonical glossary locking proper nouns and superhero names across pages.
CREATE TABLE IF NOT EXISTS terminology_store (
    source_term TEXT PRIMARY KEY,
    canonical_uzbek TEXT NOT NULL,
    entry_type TEXT NOT NULL,
    method TEXT NOT NULL,
    first_seen_page TEXT DEFAULT 'auto',
    locked BOOLEAN DEFAULT TRUE,
    reason TEXT,
    aliases JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_terminology_store_type ON terminology_store (entry_type);
CREATE INDEX IF NOT EXISTS idx_terminology_store_locked ON terminology_store (locked);

-- ==============================================================================
-- Row Level Security (RLS) Policies
-- Allow read & write access via anon / service key for Comic Translation Studio
-- ==============================================================================
ALTER TABLE mask_corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality_gate_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE character_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE terminology_store ENABLE ROW LEVEL SECURITY;

-- Anonymous / Service role full access policies
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mask_corrections' AND policyname = 'Allow anon all on mask_corrections') THEN
        CREATE POLICY "Allow anon all on mask_corrections" ON mask_corrections FOR ALL TO anon USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'quality_gate_events' AND policyname = 'Allow anon all on quality_gate_events') THEN
        CREATE POLICY "Allow anon all on quality_gate_events" ON quality_gate_events FOR ALL TO anon USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'character_profiles' AND policyname = 'Allow anon all on character_profiles') THEN
        CREATE POLICY "Allow anon all on character_profiles" ON character_profiles FOR ALL TO anon USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'terminology_store' AND policyname = 'Allow anon all on terminology_store') THEN
        CREATE POLICY "Allow anon all on terminology_store" ON terminology_store FOR ALL TO anon USING (true) WITH CHECK (true);
    END IF;
END $$;
